// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.17.3
// source: message/messagepb/message.proto

package messagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type messageing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *messageing) Reset() {
	*x = messageing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_messagepb_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *messageing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*messageing) ProtoMessage() {}

func (x *messageing) ProtoReflect() protoreflect.Message {
	mi := &file_message_messagepb_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use messageing.ProtoReflect.Descriptor instead.
func (*messageing) Descriptor() ([]byte, []int) {
	return file_message_messagepb_message_proto_rawDescGZIP(), []int{0}
}

func (x *messageing) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *messageing) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type messageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	messageing *messageing `protobuf:"bytes,1,opt,name=messageing,proto3" json:"messageing,omitempty"`
}

func (x *messageRequest) Reset() {
	*x = messageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_messagepb_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *messageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*messageRequest) ProtoMessage() {}

func (x *messageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_messagepb_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use messageRequest.ProtoReflect.Descriptor instead.
func (*messageRequest) Descriptor() ([]byte, []int) {
	return file_message_messagepb_message_proto_rawDescGZIP(), []int{1}
}

func (x *messageRequest) Getmessageing() *messageing {
	if x != nil {
		return x.messageing
	}
	return nil
}

type messageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *messageResponse) Reset() {
	*x = messageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_messagepb_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *messageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*messageResponse) ProtoMessage() {}

func (x *messageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_messagepb_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use messageResponse.ProtoReflect.Descriptor instead.
func (*messageResponse) Descriptor() ([]byte, []int) {
	return file_message_messagepb_message_proto_rawDescGZIP(), []int{2}
}

func (x *messageResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type messageManyTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	messageing *messageing `protobuf:"bytes,1,opt,name=messageing,proto3" json:"messageing,omitempty"`
}

func (x *messageManyTimeRequest) Reset() {
	*x = messageManyTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_messagepb_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *messageManyTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*messageManyTimeRequest) ProtoMessage() {}

func (x *messageManyTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_messagepb_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use messageManyTimeRequest.ProtoReflect.Descriptor instead.
func (*messageManyTimeRequest) Descriptor() ([]byte, []int) {
	return file_message_messagepb_message_proto_rawDescGZIP(), []int{3}
}

func (x *messageManyTimeRequest) Getmessageing() *messageing {
	if x != nil {
		return x.messageing
	}
	return nil
}

type messageManyTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *messageManyTimeResponse) Reset() {
	*x = messageManyTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_messagepb_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *messageManyTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*messageManyTimeResponse) ProtoMessage() {}

func (x *messageManyTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_messagepb_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use messageManyTimeResponse.ProtoReflect.Descriptor instead.
func (*messageManyTimeResponse) Descriptor() ([]byte, []int) {
	return file_message_messagepb_message_proto_rawDescGZIP(), []int{4}
}

func (x *messageManyTimeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type LongmessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	messageing *messageing `protobuf:"bytes,1,opt,name=messageing,proto3" json:"messageing,omitempty"`
}

func (x *LongmessageRequest) Reset() {
	*x = LongmessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_messagepb_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongmessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongmessageRequest) ProtoMessage() {}

func (x *LongmessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_messagepb_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongmessageRequest.ProtoReflect.Descriptor instead.
func (*LongmessageRequest) Descriptor() ([]byte, []int) {
	return file_message_messagepb_message_proto_rawDescGZIP(), []int{5}
}

func (x *LongmessageRequest) Getmessageing() *messageing {
	if x != nil {
		return x.messageing
	}
	return nil
}

type LongmessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *LongmessageResponse) Reset() {
	*x = LongmessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_messagepb_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LongmessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongmessageResponse) ProtoMessage() {}

func (x *LongmessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_messagepb_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongmessageResponse.ProtoReflect.Descriptor instead.
func (*LongmessageResponse) Descriptor() ([]byte, []int) {
	return file_message_messagepb_message_proto_rawDescGZIP(), []int{6}
}

func (x *LongmessageResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type messageEveryOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	messageing *messageing `protobuf:"bytes,1,opt,name=messageing,proto3" json:"messageing,omitempty"`
}

func (x *messageEveryOneRequest) Reset() {
	*x = messageEveryOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_messagepb_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *messageEveryOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*messageEveryOneRequest) ProtoMessage() {}

func (x *messageEveryOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_messagepb_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use messageEveryOneRequest.ProtoReflect.Descriptor instead.
func (*messageEveryOneRequest) Descriptor() ([]byte, []int) {
	return file_message_messagepb_message_proto_rawDescGZIP(), []int{7}
}

func (x *messageEveryOneRequest) Getmessageing() *messageing {
	if x != nil {
		return x.messageing
	}
	return nil
}

type messageEveryOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *messageEveryOneResponse) Reset() {
	*x = messageEveryOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_messagepb_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *messageEveryOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*messageEveryOneResponse) ProtoMessage() {}

func (x *messageEveryOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_messagepb_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use messageEveryOneResponse.ProtoReflect.Descriptor instead.
func (*messageEveryOneResponse) Descriptor() ([]byte, []int) {
	return file_message_messagepb_message_proto_rawDescGZIP(), []int{8}
}

func (x *messageEveryOneResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_message_messagepb_message_proto protoreflect.FileDescriptor

var file_message_messagepb_message_proto_rawDesc = []byte{
	0x0a, 0x19, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2f,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x72, 0x65,
	0x65, 0x74, 0x70, 0x62, 0x22, 0x44, 0x0a, 0x08, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x0c, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x27, 0x0a, 0x0d, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x45, 0x0a, 0x14, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x41, 0x0a, 0x10, 0x4c, 0x6f,
	0x6e, 0x67, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d,
	0x0a, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x2b, 0x0a,
	0x11, 0x4c, 0x6f, 0x6e, 0x67, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x45, 0x0a, 0x14, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x72, 0x65, 0x65, 0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0xb2, 0x02, 0x0a, 0x0c, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x74, 0x12, 0x15, 0x2e, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x2e, 0x67,
	0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x79, 0x54,
	0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x44, 0x0a,
	0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x47, 0x72, 0x65, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x65,
	0x65, 0x74, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x6e, 0x67, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2e,
	0x4c, 0x6f, 0x6e, 0x67, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x28, 0x01, 0x12, 0x52, 0x0a, 0x0d, 0x47, 0x72, 0x65, 0x65, 0x74, 0x45, 0x76, 0x65, 0x72,
	0x79, 0x6f, 0x6e, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2e, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_message_messagepb_message_proto_rawDescOnce sync.Once
	file_message_messagepb_message_proto_rawDescData = file_message_messagepb_message_proto_rawDesc
)

func file_message_messagepb_message_proto_rawDescGZIP() []byte {
	file_message_messagepb_message_proto_rawDescOnce.Do(func() {
		file_message_messagepb_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_messagepb_message_proto_rawDescData)
	})
	return file_message_messagepb_message_proto_rawDescData
}

var file_message_messagepb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_message_messagepb_message_proto_goTypes = []interface{}{
	(*messageing)(nil),              // 0: messagepb.messageing
	(*messageRequest)(nil),          // 1: messagepb.messageRequest
	(*messageResponse)(nil),         // 2: messagepb.messageResponse
	(*messageManyTimeRequest)(nil),  // 3: messagepb.messageManyTimeRequest
	(*messageManyTimeResponse)(nil), // 4: messagepb.messageManyTimeResponse
	(*LongmessageRequest)(nil),      // 5: messagepb.LongmessageRequest
	(*LongmessageResponse)(nil),     // 6: messagepb.LongmessageResponse
	(*messageEveryOneRequest)(nil),  // 7: messagepb.messageEveryOneRequest
	(*messageEveryOneResponse)(nil), // 8: messagepb.messageEveryOneResponse
}
var file_message_messagepb_message_proto_depIdxs = []int32{
	0, // 0: messagepb.messageRequest.messageing:type_name -> messagepb.messageing
	0, // 1: messagepb.messageManyTimeRequest.messageing:type_name -> messagepb.messageing
	0, // 2: messagepb.LongmessageRequest.messageing:type_name -> messagepb.messageing
	0, // 3: messagepb.messageEveryOneRequest.messageing:type_name -> messagepb.messageing
	1, // 4: messagepb.messageService.message:input_type -> messagepb.messageRequest
	3, // 5: messagepb.messageService.messageManyTime:input_type -> messagepb.messageManyTimeRequest
	5, // 6: messagepb.messageService.Longmessage:input_type -> messagepb.LongmessageRequest
	7, // 7: messagepb.messageService.messageEveryone:input_type -> messagepb.messageEveryOneRequest
	2, // 8: messagepb.messageService.message:output_type -> messagepb.messageResponse
	4, // 9: messagepb.messageService.messageManyTime:output_type -> messagepb.messageManyTimeResponse
	6, // 10: messagepb.messageService.Longmessage:output_type -> messagepb.LongmessageResponse
	8, // 11: messagepb.messageService.messageEveryone:output_type -> messagepb.messageEveryOneResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_messagepb_message_proto_init() }
func file_message_messagepb_message_proto_init() {
	if File_message_messagepb_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_messagepb_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*messageing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_messagepb_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*messageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_messagepb_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*messageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_messagepb_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*messageManyTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_messagepb_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*messageManyTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_messagepb_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongmessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_messagepb_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LongmessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_messagepb_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*messageEveryOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_messagepb_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*messageEveryOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_messagepb_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_messagepb_message_proto_goTypes,
		DependencyIndexes: file_message_messagepb_message_proto_depIdxs,
		MessageInfos:      file_message_messagepb_message_proto_msgTypes,
	}.Build()
	File_message_messagepb_message_proto = out.File
	file_message_messagepb_message_proto_rawDesc = nil
	file_message_messagepb_message_proto_goTypes = nil
	file_message_messagepb_message_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// messageServiceClient is the client API for messageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type messageServiceClient interface {
	message(ctx context.Context, in *messageRequest, opts ...grpc.CallOption) (*messageResponse, error)
	messageManyTime(ctx context.Context, in *messageManyTimeRequest, opts ...grpc.CallOption) (messageService_messageManyTimeClient, error)
	Longmessage(ctx context.Context, opts ...grpc.CallOption) (messageService_LongmessageClient, error)
	messageEveryone(ctx context.Context, opts ...grpc.CallOption) (messageService_messageEveryoneClient, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewmessageServiceClient(cc grpc.ClientConnInterface) messageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) message(ctx context.Context, in *messageRequest, opts ...grpc.CallOption) (*messageResponse, error) {
	out := new(messageResponse)
	err := c.cc.Invoke(ctx, "/messagepb.messageService/message", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) messageManyTime(ctx context.Context, in *messageManyTimeRequest, opts ...grpc.CallOption) (messageService_messageManyTimeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_messageService_serviceDesc.Streams[0], "/messagepb.messageService/messageManyTime", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageServicemessageManyTimeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type messageService_messageManyTimeClient interface {
	Recv() (*messageManyTimeResponse, error)
	grpc.ClientStream
}

type messageServicemessageManyTimeClient struct {
	grpc.ClientStream
}

func (x *messageServicemessageManyTimeClient) Recv() (*messageManyTimeResponse, error) {
	m := new(messageManyTimeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageServiceClient) Longmessage(ctx context.Context, opts ...grpc.CallOption) (messageService_LongmessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_messageService_serviceDesc.Streams[1], "/messagepb.messageService/Longmessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageServiceLongmessageClient{stream}
	return x, nil
}

type messageService_LongmessageClient interface {
	Send(*LongmessageRequest) error
	CloseAndRecv() (*LongmessageResponse, error)
	grpc.ClientStream
}

type messageServiceLongmessageClient struct {
	grpc.ClientStream
}

func (x *messageServiceLongmessageClient) Send(m *LongmessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageServiceLongmessageClient) CloseAndRecv() (*LongmessageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LongmessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageServiceClient) messageEveryone(ctx context.Context, opts ...grpc.CallOption) (messageService_messageEveryoneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_messageService_serviceDesc.Streams[2], "/messagepb.messageService/messageEveryone", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageServicemessageEveryoneClient{stream}
	return x, nil
}

type messageService_messageEveryoneClient interface {
	Send(*messageEveryOneRequest) error
	Recv() (*messageEveryOneResponse, error)
	grpc.ClientStream
}

type messageServicemessageEveryoneClient struct {
	grpc.ClientStream
}

func (x *messageServicemessageEveryoneClient) Send(m *messageEveryOneRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageServicemessageEveryoneClient) Recv() (*messageEveryOneResponse, error) {
	m := new(messageEveryOneResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// messageServiceServer is the server API for messageService service.
type messageServiceServer interface {
	message(context.Context, *messageRequest) (*messageResponse, error)
	messageManyTime(*messageManyTimeRequest, messageService_messageManyTimeServer) error
	Longmessage(messageService_LongmessageServer) error
	messageEveryone(messageService_messageEveryoneServer) error
}

// UnimplementedmessageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedmessageServiceServer struct {
}

func (*UnimplementedmessageServiceServer) message(context.Context, *messageRequest) (*messageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method message not implemented")
}
func (*UnimplementedmessageServiceServer) messageManyTime(*messageManyTimeRequest, messageService_messageManyTimeServer) error {
	return status.Errorf(codes.Unimplemented, "method messageManyTime not implemented")
}
func (*UnimplementedmessageServiceServer) Longmessage(messageService_LongmessageServer) error {
	return status.Errorf(codes.Unimplemented, "method Longmessage not implemented")
}
func (*UnimplementedmessageServiceServer) messageEveryone(messageService_messageEveryoneServer) error {
	return status.Errorf(codes.Unimplemented, "method messageEveryone not implemented")
}

func RegistermessageServiceServer(s *grpc.Server, srv messageServiceServer) {
	s.RegisterService(&_messageService_serviceDesc, srv)
}

func _messageService_message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(messageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(messageServiceServer).message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messagepb.messageService/message",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(messageServiceServer).message(ctx, req.(*messageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _messageService_messageManyTime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(messageManyTimeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(messageServiceServer).messageManyTime(m, &messageServicemessageManyTimeServer{stream})
}

type messageService_messageManyTimeServer interface {
	Send(*messageManyTimeResponse) error
	grpc.ServerStream
}

type messageServicemessageManyTimeServer struct {
	grpc.ServerStream
}

func (x *messageServicemessageManyTimeServer) Send(m *messageManyTimeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _messageService_Longmessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(messageServiceServer).Longmessage(&messageServiceLongmessageServer{stream})
}

type messageService_LongmessageServer interface {
	SendAndClose(*LongmessageResponse) error
	Recv() (*LongmessageRequest, error)
	grpc.ServerStream
}

type messageServiceLongmessageServer struct {
	grpc.ServerStream
}

func (x *messageServiceLongmessageServer) SendAndClose(m *LongmessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageServiceLongmessageServer) Recv() (*LongmessageRequest, error) {
	m := new(LongmessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _messageService_messageEveryone_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(messageServiceServer).messageEveryone(&messageServicemessageEveryoneServer{stream})
}

type messageService_messageEveryoneServer interface {
	Send(*messageEveryOneResponse) error
	Recv() (*messageEveryOneRequest, error)
	grpc.ServerStream
}

type messageServicemessageEveryoneServer struct {
	grpc.ServerStream
}

func (x *messageServicemessageEveryoneServer) Send(m *messageEveryOneResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageServicemessageEveryoneServer) Recv() (*messageEveryOneRequest, error) {
	m := new(messageEveryOneRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _messageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messagepb.messageService",
	HandlerType: (*messageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "message",
			Handler:    _messageService_message_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "messageManyTime",
			Handler:       _messageService_messageManyTime_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Longmessage",
			Handler:       _messageService_Longmessage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "messageEveryone",
			Handler:       _messageService_messageEveryone_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message/messagepb/message.proto",
}
